RDS_TMC_EVENTS={
  1:"traffic problem",
  101:"stationary traffic",
  102:"stationary traffic for 1 km",
  103:"stationary traffic for 2 km",
  129:"stationary traffic for 3 km",
  104:"stationary traffic for 4 km",
  105:"stationary traffic for 6 km",
  106:"stationary traffic for 10 km",
  130:"danger of stationary traffic",
  108:"queuing traffic (with average speeds Q)::of up to S km/h",
  109:"queuing traffic for 1 km (with average speeds Q)::of up to S km/h",
  110:"queuing traffic for 2 km (with average speeds Q)::of up to S km/h",
  131:"queuing traffic for 3 km (with average speeds Q)::of up to S km/h",
  111:"queuing traffic for 4 km (with average speeds Q)::of up to S km/h",
  112:"queuing traffic for 6 km (with average speeds Q)::of up to S km/h",
  113:"queuing traffic for 10 km (with average speeds Q)::of up to S km/h",
  132:"danger of queuing traffic (with average speeds Q)::of up to S km/h",
  133:"long queues (with average speeds Q)::of up to S km/h",
  115:"slow traffic (with average speeds Q)::of up to S km/h",
  116:"slow traffic for 1 km (with average speeds Q)::of up to S km/h",
  117:"slow traffic for 2 km (with average speeds Q)::of up to S km/h",
  134:"slow traffic for 3 km (with average speeds Q)::of up to S km/h",
  118:"slow traffic for 4 km (with average speeds Q)::of up to S km/h",
  119:"slow traffic for 6 km (with average speeds Q)::of up to S km/h",
  120:"slow traffic for 10 km (with average speeds Q)::of up to S km/h",
  122:"heavy traffic (with average speeds Q)::of up to S km/h",
  142:"traffic heavier than normal (with average speeds Q)::of up to S km/h",
  143:"traffic very much heavier than normal (with average speeds Q)::of up to S km/h",
  124:"traffic flowing freely (with average speeds Q)::of up to S km/h",
  125:"traffic building up (with average speeds Q)::of up to S km/h",
  135:"traffic easing::of up to S km/h",
  136:"traffic congestion (with average speeds Q)::of up to S km/h",
  70:"traffic congestion, average speed of 10 km/h",
  71:"traffic congestion, average speed of 20 km/h",
  72:"traffic congestion, average speed of 30 km/h",
  73:"traffic congestion, average speed of 40 km/h",
  74:"traffic congestion, average speed of 50 km/h",
  75:"traffic congestion, average speed of 60 km/h",
  76:"traffic congestion, average speed of 70 km/h",
  137:"traffic lighter than normal (with average speeds Q)::of up to S km/h",
  138:"queuing traffic (with average speeds Q). Approach with care::of up to S km/h",
  139:"queuing traffic around a bend in the road",
  140:"queuing traffic over the crest of a hill",
  2:"queuing traffic (with average speeds Q). Danger of stationary traffic::of up to S km/h",
  215:"(Q) accident(s). Stationary traffic::n (small number)",
  216:"(Q) accident(s). Stationary traffic for 1 km::n (small number)",
  217:"(Q) accident(s). Stationary traffic for 2 km::n (small number)",
  348:"(Q) accident(s). Stationary traffic for 3 km::n (small number)",
  218:"(Q) accident(s). Stationary traffic for 4 km::n (small number)",
  219:"(Q) accident(s). Stationary traffic for 6 km::n (small number)",
  220:"(Q) accident(s). Stationary traffic for 10 km::n (small number)",
  221:"(Q) accident(s). Danger of stationary traffic::n (small number)",
  222:"(Q) accident(s). Queuing traffic::n (small number)",
  223:"(Q) accident(s). Queuing traffic for 1 km::n (small number)",
  224:"(Q) accident(s). Queuing traffic for 2 km::n (small number)",
  349:"(Q) accident(s). Queuing traffic for 3 km::n (small number)",
  225:"(Q) accident(s). Queuing traffic for 4 km::n (small number)",
  226:"(Q) accident(s). Queuing traffic for 6 km::n (small number)",
  227:"(Q) accident(s). Queuing traffic for 10 km::n (small number)",
  228:"(Q) accident(s). Danger of queuing traffic::n (small number)",
  229:"(Q) accident(s). Slow traffic::n (small number)",
  230:"(Q) accident(s). Slow traffic for 1 km::n (small number)",
  231:"(Q) accident(s). Slow traffic for 2 km::n (small number)",
  350:"(Q) accident(s). Slow traffic for 3 km::n (small number)",
  232:"(Q) accident(s). Slow traffic for 4 km::n (small number)",
  233:"(Q) accident(s). Slow traffic for 6 km::n (small number)",
  234:"(Q) accident(s). Slow traffic for 10 km::n (small number)",
  236:"(Q) accident(s). Heavy traffic::n (small number)",
  238:"(Q) accident(s). Traffic flowing freely::n (small number)",
  239:"(Q) accident(s). Traffic building up::n (small number)",
  250:"vehicles slowing to look at (Q) accident(s). Stationary traffic::n (small number)",
  251:"vehicles slowing to look at (Q) accident(s). Stationary traffic for 1 km::n (small number)",
  252:"vehicles slowing to look at (Q) accident(s). Stationary traffic for 2 km::n (small number)",
  352:"vehicles slowing to look at (Q) accident(s). Stationary traffic for 3 km::n (small number)",
  253:"vehicles slowing to look at (Q) accident(s). Stationary traffic for 4 km::n (small number)",
  254:"vehicles slowing to look at (Q) accident(s). Stationary traffic for 6 km::n (small number)",
  255:"vehicles slowing to look at (Q) accident(s). Stationary traffic for 10 km::n (small number)",
  256:"vehicles slowing to look at (Q) accident(s). Danger of stationary traffic::n (small number)",
  257:"vehicles slowing to look at (Q) accident(s). Queuing traffic::n (small number)",
  258:"vehicles slowing to look at (Q) accident(s). Queuing traffic for 1 km::n (small number)",
  259:"vehicles slowing to look at (Q) accident(s). Queuing traffic for 2 km::n (small number)",
  353:"vehicles slowing to look at (Q) accident(s). Queuing traffic for 3 km::n (small number)",
  260:"vehicles slowing to look at (Q) accident(s). Queuing traffic for 4 km::n (small number)",
  261:"vehicles slowing to look at (Q) accident(s). Queuing traffic for 6 km::n (small number)",
  262:"vehicles slowing to look at (Q) accident(s). Queuing traffic for 10 km::n (small number)",
  263:"vehicles slowing to look at (Q) accident(s). Danger of queuing traffic::n (small number)",
  208:"vehicles slowing to look at (Q) accident(s)::n (small number)",
  264:"vehicles slowing to look at (Q) accident(s). Slow traffic::n (small number)",
  265:"vehicles slowing to look at (Q) accident(s). Slow traffic for 1 km::n (small number)",
  266:"vehicles slowing to look at (Q) accident(s). Slow traffic for 2 km::n (small number)",
  354:"vehicles slowing to look at (Q) accident(s). Slow traffic for 3 km::n (small number)",
  267:"vehicles slowing to look at (Q) accident(s). Slow traffic for 4 km::n (small number)",
  268:"vehicles slowing to look at (Q) accident(s). Slow traffic for 6 km::n (small number)",
  269:"vehicles slowing to look at (Q) accident(s). Slow traffic for 10 km::n (small number)",
  271:"vehicles slowing to look at (Q) accident(s). Heavy traffic::n (small number)",
  274:"vehicles slowing to look at (Q) accident(s). Traffic building up::n (small number)",
  355:"vehicles slowing to look at (Q) accident(s). Danger::n (small number)",
  278:"(Q) shed load(s). Stationary traffic::n (small number)",
  279:"(Q) shed load(s). Stationary traffic for 1 km::n (small number)",
  280:"(Q) shed load(s). Stationary traffic for 2 km::n (small number)",
  356:"(Q) shed load(s). Stationary traffic for 3 km::n (small number)",
  281:"(Q) shed load(s). Stationary traffic for 4 km::n (small number)",
  282:"(Q) shed load(s). Stationary traffic for 6 km::n (small number)",
  283:"(Q) shed load(s). Stationary traffic for 10 km::n (small number)",
  284:"(Q) shed load(s). Danger of stationary traffic::n (small number)",
  285:"(Q) shed load(s). Queuing traffic::n (small number)",
  286:"(Q) shed load(s). Queuing traffic for 1 km::n (small number)",
  287:"(Q) shed load(s). Queuing traffic for 2 km::n (small number)",
  357:"(Q) shed load(s). Queuing traffic for 3 km::n (small number)",
  288:"(Q) shed load(s). Queuing traffic for 4 km::n (small number)",
  289:"(Q) shed load(s). Queuing traffic for 6 km::n (small number)",
  290:"(Q) shed load(s). Queuing traffic for 10 km::n (small number)",
  291:"(Q) shed load(s). Danger of queuing traffic::n (small number)",
  292:"(Q) shed load(s). Slow traffic::n (small number)",
  293:"(Q) shed load(s). Slow traffic for 1 km::n (small number)",
  294:"(Q) shed load(s). Slow traffic for 2 km::n (small number)",
  358:"(Q) shed load(s). Slow traffic for 3 km::n (small number)",
  295:"(Q) shed load(s). Slow traffic for 4 km::n (small number)",
  296:"(Q) shed load(s). Slow traffic for 6 km::n (small number)",
  297:"(Q) shed load(s). Slow traffic for 10 km::n (small number)",
  299:"(Q) shed load(s). Heavy traffic::n (small number)",
  301:"(Q) shed load(s). Traffic flowing freely::n (small number)",
  302:"(Q) shed load(s). Traffic building up::n (small number)",
  360:"(Q) overturned vehicle(s). Stationary traffic::n (small number)",
  361:"(Q) overturned vehicle(s). Danger of stationary traffic::n (small number)",
  362:"(Q) overturned vehicle(s). Queuing traffic::n (small number)",
  363:"(Q) overturned vehicle(s). Danger of queuing traffic::n (small number)",
  364:"(Q) overturned vehicle(s). Slow traffic::n (small number)",
  366:"(Q) overturned vehicle(s). Heavy traffic::n (small number)",
  368:"(Q) overturned vehicle(s). Traffic building up::n (small number)",
  379:"Stationary traffic due to (Q) earlier accident(s)::n (small number)",
  380:"Danger of stationary traffic due to (Q) earlier accident(s)::n (small number)",
  381:"Queuing traffic due to (Q) earlier accident(s)::n (small number)",
  382:"Danger of queuing traffic due to (Q) earlier accident(s)::n (small number)",
  383:"Slow traffic due to (Q) earlier accident(s)::n (small number)",
  385:"Heavy traffic due to (Q) earlier accident(s)::n (small number)",
  387:"Traffic building up due to (Q) earlier accident(s)::n (small number)",
  313:"(Q) broken down vehicle(s). Stationary traffic::n (small number)",
  314:"(Q) broken down vehicle(s). Danger of stationary traffic::n (small number)",
  315:"(Q) broken down vehicle(s). Queuing traffic::n (small number)",
  316:"(Q) broken down vehicle(s). Danger of queuing traffic::n (small number)",
  317:"(Q) broken down vehicle(s). Slow traffic::n (small number)",
  319:"(Q) broken down vehicle(s). Heavy traffic::n (small number)",
  321:"(Q) broken down vehicle(s). Traffic flowing freely::n (small number)",
  322:"(Q) broken down vehicle(s). Traffic building up::n (small number)",
  410:"closed ahead. Stationary traffic",
  411:"closed ahead. Stationary traffic for 1 km",
  412:"closed ahead. Stationary traffic for 2 km",
  495:"closed ahead. Stationary traffic for 3 km",
  413:"closed ahead. Stationary traffic for 4 km",
  414:"closed ahead. Stationary traffic for 6 km",
  415:"closed ahead. Stationary traffic for 10 km",
  416:"closed ahead. Danger of stationary traffic",
  417:"closed ahead. Queuing traffic",
  418:"closed ahead. Queuing traffic for 1 km",
  419:"closed ahead. Queuing traffic for 2 km",
  496:"closed ahead. Queuing traffic for 3 km",
  420:"closed ahead. Queuing traffic for 4 km",
  421:"closed ahead. Queuing traffic for 6 km",
  422:"closed ahead. Queuing traffic for 10 km",
  423:"closed ahead. Danger of queuing traffic",
  424:"closed ahead. Slow traffic",
  425:"closed ahead. Slow traffic for 1 km",
  426:"closed ahead. Slow traffic for 2 km",
  497:"closed ahead. Slow traffic for 3 km",
  427:"closed ahead. Slow traffic for 4 km",
  428:"closed ahead. Slow traffic for 6 km",
  429:"closed ahead. Slow traffic for 10 km",
  431:"closed ahead. Heavy traffic",
  433:"closed ahead. Traffic flowing freely",
  434:"closed ahead. Traffic building up",
  438:"blocked ahead. Stationary traffic",
  439:"blocked ahead. Stationary traffic for 1 km",
  440:"blocked ahead. Stationary traffic for 2 km",
  498:"blocked ahead. Stationary traffic for 3 km",
  441:"blocked ahead. Stationary traffic for 4 km",
  442:"blocked ahead. Stationary traffic for 6 km",
  443:"blocked ahead. Stationary traffic for 10 km",
  444:"blocked ahead. Danger of stationary traffic",
  445:"blocked ahead. Queuing traffic",
  446:"blocked ahead. Queuing traffic for 1 km",
  447:"blocked ahead. Queuing traffic for 2 km",
  499:"blocked ahead. Queuing traffic for 3 km",
  448:"blocked ahead. Queuing traffic for 4 km",
  449:"blocked ahead. Queuing traffic for 6 km",
  450:"blocked ahead. Queuing traffic for 10 km",
  451:"blocked ahead. Danger of queuing traffic",
  452:"blocked ahead. Slow traffic",
  453:"blocked ahead. Slow traffic for 1 km",
  454:"blocked ahead. Slow traffic for 2 km",
  626:"blocked ahead. Slow traffic for 3 km",
  455:"blocked ahead. Slow traffic for 4 km",
  456:"blocked ahead. Slow traffic for 6 km",
  457:"blocked ahead. Slow traffic for 10 km",
  459:"blocked ahead. Heavy traffic",
  461:"blocked ahead. Traffic flowing freely",
  462:"blocked ahead. Traffic building up",
  521:"(Q) lanes closed. Stationary traffic::n (small number)",
  522:"(Q) lanes closed. Stationary traffic for 1 km::n (small number)",
  523:"(Q) lanes closed. Stationary traffic for 2 km::n (small number)",
  651:"(Q) lanes closed. Stationary traffic for 3 km::n (small number)",
  524:"(Q) lanes closed. Stationary traffic for 4 km::n (small number)",
  525:"(Q) lanes closed. Stationary traffic for 6 km::n (small number)",
  526:"(Q) lanes closed. Stationary traffic for 10 km::n (small number)",
  527:"(Q) lanes closed. Danger of stationary traffic::n (small number)",
  528:"(Q) lanes closed. Queuing traffic::n (small number)",
  529:"(Q) lanes closed. Queuing traffic for 1 km::n (small number)",
  530:"(Q) lanes closed. Queuing traffic for 2 km::n (small number)",
  652:"(Q) lanes closed. Queuing traffic for 3 km::n (small number)",
  531:"(Q) lanes closed. Queuing traffic for 4 km::n (small number)",
  532:"(Q) lanes closed. Queuing traffic for 6 km::n (small number)",
  533:"(Q) lanes closed. Queuing traffic for 10 km::n (small number)",
  534:"(Q) lanes closed. Danger of queuing traffic::n (small number)",
  535:"(Q) lanes closed. Slow traffic::n (small number)",
  536:"(Q) lanes closed. Slow traffic for 1 km::n (small number)",
  537:"(Q) lanes closed. Slow traffic for 2 km::n (small number)",
  653:"(Q) lanes closed. Slow traffic for 3 km::n (small number)",
  538:"(Q) lanes closed. Slow traffic for 4 km::n (small number)",
  539:"(Q) lanes closed. Slow traffic for 6 km::n (small number)",
  540:"(Q) lanes closed. Slow traffic for 10 km::n (small number)",
  542:"(Q) lanes closed. Heavy traffic::n (small number)",
  544:"(Q)lanes closed. Traffic flowing freely::n (small number)",
  545:"(Q)lanes closed. Traffic building up::n (small number)",
  546:"carriageway reduced (from Q lanes) to one lane. Stationary traffic::n (small number)",
  547:"carriageway reduced (from Q lanes) to one lane. Danger of stationary traffic::n (small number)",
  548:"carriageway reduced (from Q lanes) to one lane. Queuing traffic::n (small number)",
  549:"carriageway reduced (from Q lanes) to one lane. Danger of queuing traffic::n (small number)",
  550:"carriageway reduced (from Q lanes) to one lane. Slow traffic::n (small number)",
  552:"carriageway reduced (from Q lanes) to one lane. Heavy traffic::n (small number)",
  554:"carriageway reduced (from Q lanes) to one lane. Traffic flowing freely::n (small number)",
  555:"carriageway reduced (from Q lanes) to one lane. Traffic building up::n (small number)",
  556:"carriageway reduced (from Q lanes) to two lanes. Stationary traffic::n (small number)",
  557:"carriageway reduced (from Q lanes) to two lanes. Danger of stationary traffic::n (small number)",
  558:"carriageway reduced (from Q lanes) to two lanes. Queuing traffic::n (small number)",
  559:"carriageway reduced (from Q lanes) to two lanes. Danger of queuing traffic::n (small number)",
  560:"carriageway reduced (from Q lanes) to two lanes. Slow traffic::n (small number)",
  562:"carriageway reduced (from Q lanes) to two lanes. Heavy traffic::n (small number)",
  564:"carriageway reduced (from Q lanes) to two lanes. Traffic flowing freely::n (small number)",
  565:"carriageway reduced (from Q lanes) to two lanes. Traffic building up::n (small number)",
  566:"carriageway reduced (from Q lanes) three lanes. Stationary traffic::n (small number)",
  567:"carriageway reduced (from Q lanes) three lanes. Danger of stationary traffic::n (small number)",
  568:"carriageway reduced (from Q lanes) three lanes. Queuing traffic::n (small number)",
  569:"carriageway reduced (from Q lanes) three lanes. Danger of queuing traffic::n (small number)",
  570:"carriageway reduced (from Q lanes) to three lanes. Slow traffic::n (small number)",
  572:"carriageway reduced (from Q lanes) to three lanes. Heavy traffic::n (small number)",
  574:"carriageway reduced (from Q lanes) to three lanes. Traffic flowing freely::n (small number)",
  575:"carriageway reduced (from Q lanes) to three lanes. Traffic building up::n (small number)",
  576:"contraflow. Stationary traffic",
  577:"contraflow. Stationary traffic for 1 km",
  578:"contraflow. Stationary traffic for 2 km",
  654:"contraflow. Stationary traffic for 3 km",
  579:"contraflow. Stationary traffic for 4 km",
  580:"contraflow. Stationary traffic for 6 km",
  581:"contraflow. Stationary traffic for 10 km",
  582:"contraflow. Danger of stationary traffic",
  583:"contraflow. Queuing traffic",
  584:"contraflow. Queuing traffic for1km",
  585:"contraflow. Queuing traffic for2km",
  655:"contraflow. Queuing traffic for3km",
  586:"contraflow. Queuing traffic for4km",
  587:"contraflow. Queuing traffic for6km",
  588:"contraflow. Queuing traffic for 10 km",
  589:"contraflow. Danger of queuing traffic",
  590:"contraflow. Slow traffic",
  591:"contraflow. Slow traffic for 1 km",
  592:"contraflow. Slow traffic for 2 km",
  656:"contraflow. Slow traffic for 3 km",
  593:"contraflow. Slow traffic for 4 km",
  594:"contraflow. Slow traffic for 6 km",
  595:"contraflow. Slow traffic for 10 km",
  597:"contraflow. Heavy traffic",
  599:"contraflow. Traffic flowing freely",
  600:"contraflow. Traffic building up",
  604:"narrow lanes. Stationary traffic",
  605:"narrow lanes. Danger of stationary traffic",
  606:"narrow lanes. Queuing traffic",
  607:"narrow lanes. Danger of queuing traffic",
  608:"narrow lanes. Slow traffic",
  610:"narrow lanes. Heavy traffic",
  612:"narrow lanes. Traffic flowing freely",
  613:"narrow lanes. Traffic building up",
  614:"contraflow with narrow lanes. Stationary traffic",
  615:"contraflow with narrow lanes. Danger of stationary traffic",
  616:"contraflow with narrow lanes. Queuing traffic",
  617:"contraflow with narrow lanes. Danger of queuing traffic",
  618:"contraflow with narrow lanes. Slow traffic",
  620:"contraflow with narrow lanes. Heavy traffic",
  622:"contraflow with narrow lanes. Traffic flowing freely",
  623:"contraflow with narrow lanes. Traffic building up",
  710:"(Q sets of) roadworks. Stationary traffic::n (small number)",
  711:"(Q sets of) roadworks. Stationary traffic for 1 km::n (small number)",
  712:"(Q sets of) roadworks. Stationary traffic for 2 km::n (small number)",
  812:"(Q sets of) roadworks. Stationary traffic for 3 km::n (small number)",
  713:"(Q sets of) roadworks. Stationary traffic for 4 km::n (small number)",
  714:"(Q sets of) roadworks. Stationary traffic for 6 km::n (small number)",
  715:"(Q sets of) roadworks. Stationary traffic for 10 km::n (small number)",
  716:"(Q sets of) roadworks. Danger of stationary traffic::n (small number)",
  717:"(Q sets of) roadworks. Queuing traffic::n (small number)",
  718:"(Q sets of) roadworks. Queuing traffic for 1 km::n (small number)",
  719:"(Q sets of) roadworks. Queuing traffic for 2 km::n (small number)",
  813:"(Q sets of) roadworks. Queuing traffic for 3 km::n (small number)",
  720:"(Q sets of) roadworks. Queuing traffic for 4 km::n (small number)",
  721:"(Q sets of) roadworks. Queuing traffic for 6 km::n (small number)",
  722:"(Q sets of) roadworks. Queuing traffic for 10 km::n (small number)",
  723:"(Q sets of) roadworks. Danger of queuing traffic::n (small number)",
  724:"(Q sets of) roadworks. Slow traffic::n (small number)",
  725:"(Q sets of) roadworks. Slow traffic for 1 km::n (small number)",
  726:"(Q sets of) roadworks. Slow traffic for 2 km::n (small number)",
  814:"(Q sets of) roadworks. Slow traffic for 3 km::n (small number)",
  727:"(Q sets of) roadworks. Slow traffic for 4 km::n (small number)",
  728:"(Q sets of) roadworks. Slow traffic for 6 km::n (small number)",
  729:"(Q sets of) roadworks. Slow traffic for 10 km::n (small number)",
  731:"(Q sets of) roadworks. Heavy traffic::n (small number)",
  733:"(Q sets of) roadworks. Traffic flowing freely::n (small number)",
  734:"(Q sets of) roadworks. Traffic building up::n (small number)",
  750:"(Q sections of) resurfacing work. Stationary traffic::n (small number)",
  751:"(Q sections of) resurfacing work. Stationary traffic for 1 km::n (small number)",
  752:"(Q sections of) resurfacing work. Stationary traffic for 2 km::n (small number)",
  818:"(Q sections of) resurfacing work. Stationary traffic for 3 km::n (small number)",
  753:"(Q sections of) resurfacing work. Stationary traffic for 4 km::n (small number)",
  754:"(Q sections of) resurfacing work. Stationary traffic for 6 km::n (small number)",
  755:"(Q sections of) resurfacing work. Stationary traffic for 10 km::n (small number)",
  756:"(Q sections of) resurfacing work. Danger of stationary traffic::n (small number)",
  757:"(Q sections of) resurfacing work. Queuing traffic::n (small number)",
  758:"(Q sections of) resurfacing work. Queuing traffic for 1 km::n (small number)",
  759:"(Q sections of) resurfacing work. Queuing traffic for 2 km::n (small number)",
  819:"(Q sections of) resurfacing work. Queuing traffic for 3 km::n (small number)",
  760:"(Q sections of) resurfacing work. Queuing traffic for 4 km::n (small number)",
  761:"(Q sections of) resurfacing work. Queuing traffic for 6 km::n (small number)",
  762:"(Q sections of) resurfacing work. Queuing traffic for 10 km::n (small number)",
  763:"(Q sections of) resurfacing work. Danger of queuing traffic::n (small number)",
  764:"(Q sections of) resurfacing work. traffic::n (small number)",
  765:"(Q sections of) resurfacing work. traffic for 1 km::n (small number)",
  766:"(Q sections of) resurfacing work. traffic for 2 km::n (small number)",
  820:"(Q sections of) resurfacing work. traffic for 3 km::n (small number)",
  767:"(Q sections of) resurfacing work. traffic for 4 km::n (small number)",
  768:"(Q sections of) resurfacing work. traffic for 6 km::n (small number)",
  769:"(Q sections of) resurfacing work. traffic for 10 km::n (small number)",
  771:"(Q sections of) resurfacing work. Heavy traffic::n (small number)",
  773:"(Q sections of) resurfacing work. Traffic flowing freely::n (small number)",
  774:"(Q sections of) resurfacing work. Traffic building up::n (small number)",
  783:"(Q sets of) road marking work. Stationary traffic::n (small number)",
  784:"(Q sets of) road marking work. Danger of stationary traffic::n (small number)",
  785:"(Q sets of) road marking work. Queuing traffic::n (small number)",
  786:"(Q sets of) road marking work. Danger of queuing traffic::n (small number)",
  787:"(Q sets of) road marking work. Slow traffic::n (small number)",
  789:"(Q sets of) road marking work. Heavy traffic::n (small number)",
  791:"(Q sets of) road marking work. Traffic flowing freely::n (small number)",
  792:"(Q sets of) road marking work. Traffic building up::n (small number)",
  825:"(Q sets of) slow moving maintenance vehicles. Stationary traffic::n (small number)",
  826:"(Q sets of) slow moving maintenance vehicles. Danger of stationary traffic::n (small number)",
  827:"(Q sets of) slow moving maintenance vehicles. Queuing traffic::n (small number)",
  828:"(Q sets of) slow moving maintenance vehicles. Danger of queuing traffic::n (small number)",
  829:"(Q sets of) slow moving maintenance vehicles. Slow traffic::n (small number)",
  831:"(Q sets of) slow moving maintenance vehicles. Heavy traffic::n (small number)",
  833:"(Q sets of) slow moving maintenance vehicles. Traffic flowing freely::n (small number)",
  834:"(Q sets of) slow moving maintenance vehicles. Traffic building up::n (small number)",
  928:"flooding. Stationary traffic",
  929:"flooding. Danger of stationary traffic",
  930:"flooding. Queuing traffic",
  931:"flooding. Danger of queuing traffic",
  932:"flooding. Slow traffic",
  934:"flooding. Heavy traffic",
  936:"flooding. Traffic flowing freely",
  937:"flooding. Traffic building up",
  1517:"major event. Stationary traffic",
  1518:"major event. Danger of stationary traffic",
  1519:"major event. Queuing traffic",
  1520:"major event. Danger of queuing traffic",
  1521:"major event. Slow traffic",
  1523:"major event. Heavy traffic",
  1525:"major event. Traffic flowing freely",
  1526:"major event. Traffic building up",
  1531:"sports meeting. Stationary traffic",
  1532:"sports meeting. Danger of stationary traffic",
  1533:"sports meeting. Queuing traffic",
  1534:"sports meeting. Danger of queuing traffic",
  1535:"sports meeting. Slow traffic",
  1537:"sports meeting. Heavy traffic",
  1539:"sports meeting. Traffic flowing freely",
  1540:"sports meeting. Traffic building up",
  1545:"fair. Stationary traffic",
  1546:"fair. Danger of stationary traffic",
  1547:"fair. Queuing traffic",
  1548:"fair. Danger of queuing traffic",
  1549:"fair. Slow traffic",
  1551:"fair. Heavy traffic",
  1553:"fair. Traffic flowing freely",
  1554:"fair. Traffic building up",
  1571:"security alert. Stationary traffic",
  1572:"security alert. Danger of stationary traffic",
  1573:"security alert. Queuing traffic",
  1574:"security alert. Danger of queuing traffic",
  1575:"security alert. Slow traffic",
  1577:"security alert. Heavy traffic",
  1495:"evacuation. Heavy traffic",
  1586:"security alert. Traffic flowing freely",
  1579:"security alert. Traffic building up",
  1807:"(Q sets of) traffic lights not working. Stationary traffic::n (small number)",
  1808:"(Q sets of) traffic lights not working. Danger of stationary traffic::n (small number)",
  1809:"(Q sets of) traffic lights not working. Queuing traffic::n (small number)",
  1810:"(Q sets of) traffic lights not working. Danger of queuing traffic::n (small number)",
  1811:"(Q sets of) traffic lights not working. Slow traffic::n (small number)",
  1813:"(Q sets of) traffic lights not working. Heavy traffic::n (small number)",
  1815:"(Q sets of) traffic lights not working. Traffic flowing freely::n (small number)",
  1816:"(Q sets of) traffic lights not working. Traffic building up::n (small number)",
  1820:"level crossing failure. Stationary traffic",
  1821:"level crossing failure. Danger of stationary traffic",
  1822:"level crossing failure. Queuing traffic",
  1823:"level crossing failure. Danger of queuing traffic",
  1824:"level crossing failure. Slow traffic",
  1826:"level crossing failure. Heavy traffic",
  1828:"level crossing failure. Traffic flowing freely",
  1829:"level crossing failure. Traffic building up",
  126:"no problems to report",
  127:"traffic congestion cleared",
  1584:"traffic has returned to normal",
  128:"message cancelled",
  55:"traffic problem expected",
  107:"stationary traffic expected",
  114:"queuing traffic expected",
  121:"slow traffic expected",
  123:"heavy traffic expected",
  56:"traffic congestion expected",
  235:"(Q) accident(s). Slow traffic expected::n (small number)",
  237:"(Q) accident(s). Heavy traffic expected::n (small number)",
  270:"vehicles slowing to look at (Q) accident(s). Slow traffic expected::n (small number)",
  272:"vehicles slowing to look at (Q) accident(s). Heavy traffic expected::n (small number)",
  298:"(Q) shed load(s). Slow traffic expected::n (small number)",
  300:"(Q) shed load(s). Heavy traffic expected::n (small number)",
  365:"(Q) overturned vehicle(s). Slow traffic expected::n (small number)",
  367:"(Q) overturned vehicle(s). Heavy traffic expected::n (small number)",
  318:"(Q) broken down vehicle(s). Slow traffic expected::n (small number)",
  320:"(Q) broken down vehicle(s). Heavy traffic expected::n (small number)",
  430:"closed ahead. Slow traffic expected",
  432:"closed ahead. Heavy traffic expected",
  458:"blocked ahead. Slow traffic expected",
  460:"blocked ahead. Heavy traffic expected",
  541:"(Q) lanes closed. Slow traffic expected::n (small number)",
  543:"(Q) lanes closed. Heavy traffic expected::n (small number)",
  551:"carriageway reduced (from Q lanes) to one lane. Slow traffic expected::n (small number)",
  553:"carriageway reduced (from Q lanes) to one lane. Heavy traffic expected::n (small number)",
  561:"carriageway reduced (from Q lanes) to two lanes. Slow traffic expected::n (small number)",
  563:"carriageway reduced (from Q lanes) to two lanes. Heavy traffic expected::n (small number)",
  571:"carriageway reduced (from Q lanes) to three lanes. Slow traffic expected::n (small number)",
  573:"carriageway reduced (from Q lanes) to three lanes. Heavy traffic expected::n (small number)",
  596:"contraflow. Slow traffic expected",
  598:"contraflow. Heavy traffic expected",
  609:"narrow lanes. Slow traffic expected",
  611:"narrow lanes. Heavy traffic expected",
  619:"contraflow with narrow lanes. Slow traffic expected",
  621:"contraflow with narrow lanes. Heavy traffic expected",
  730:"(Q sets of) roadworks. Slow traffic expected::n (small number)",
  732:"(Q sets of) roadworks. Heavy traffic expected::n (small number)",
  770:"(Q sections of) resurfacing work. Slow traffic expected::n (small number)",
  772:"(Q sections of) resurfacing work. Heavy traffic expected::n (small number)",
  788:"(Q sets of) road marking work. Slow traffic expected::n (small number)",
  790:"(Q sets of) road marking work. Heavy traffic expected::n (small number)",
  830:"(Q sets of) slow moving maintenance vehicles. Slow traffic expected::n (small number)",
  832:"(Q sets of) slow moving maintenance vehicles. Heavy traffic expected::n (small number)",
  933:"flooding. Slow traffic expected",
  935:"flooding. Heavy traffic expected",
  1522:"major event. Slow traffic expected",
  1524:"major event. Heavy traffic expected",
  1536:"sports meeting. Slow traffic expected",
  1538:"sports meeting. Heavy traffic expected",
  1550:"fair. Slow traffic expected",
  1552:"fair. Heavy traffic expected",
  1576:"security alert. Slow traffic expected",
  1578:"security alert. Heavy traffic expected",
  1812:"(Q sets of) traffic lights not working. Slow traffic expected::n (small number)",
  1814:"(Q sets of) traffic lights not working. Heavy traffic expected::n (small number)",
  1825:"level crossing failure. Slow traffic expected",
  1827:"level crossing failure. Heavy traffic expected",
  57:"normal traffic expected",
  1589:"message cancelled",
  201:"(Q) accident(s)::n (small number)",
  202:"(Q) serious accident(s)::n (small number)",
  203:"multi-vehicle accident (involving Q vehicles)::n (small number)",
  204:"accident involving (a/Q) heavy lorr(y/ies)::n (small number)",
  335:"accident involving (a/Q) bus(es)::n (small number)",
  205:"(Q) accident(s) involving hazardous materials::n (small number)",
  206:"(Q) fuel spillage accident(s)::n (small number)",
  207:"(Q) chemical spillage accident(s)::n (small number)",
  336:"(Q) oil spillage accident(s)::n (small number)",
  337:"(Q) overturned vehicle(s)::n (small number)",
  338:"(Q) overturned heavy lorr(y/ies)::n (small number)",
  339:"(Q) jack-knifed trailer(s)::n (small number)",
  340:"(Q) jack-knifed caravan(s)::n (small number)",
  341:"(Q) jack-knifed articulated lorr(y/ies)::n (small number)",
  213:"(Q) vehicle fire(s)::n (small number)",
  342:"(Q) vehicle(s) spun around::n (small number)",
  378:"(Q) overturned vehicle(s). Danger::n (small number)",
  343:"(Q) earlier accident(s)::n (small number)",
  344:"accident investigation work",
  391:"accident investigation work. Danger",
  351:"(Q) accident(s) in roadworks area::n (small number)",
  12:"(Q) accident(s), traffic being directed around accident area::n (small number)",
  345:"(Q) secondary accident(s)::n (small number)",
  392:"(Q) secondary accident(s). Danger::n (small number)",
  209:"(Q) accident(s) in the opposing lanes::n (small number)",
  141:"all accidents cleared, no problems to report",
  333:"accident cleared",
  334:"message cancelled",
  214:"(Q) incident(s)::n (small number)",
  211:"(Q) broken down vehicle(s)::n (small number)",
  393:"(Q) broken down vehicle(s). Danger::n (small number)",
  212:"(Q) broken down heavy lorr(y/ies)::n (small number)",
  394:"(Q) broken down heavy lorr(y/ies). Danger::n (small number)",
  346:"(Q) broken down bus(es)::n (small number)",
  11:"over-height warning system triggered",
  924:"clearance work",
  1034:"clearance work. Danger",
  397:"rescue and recovery work in progress",
  1066:"rescue and recovery work in progress. Danger",
  396:"incident cleared",
  395:"road cleared",
  2028:"message cancelled",
  666:"intermittent short term closures",
  401:"Closed",
  240:"road closed due to (Q) accident(s)::n (small number)",
  16:"closed, rescue and recovery work in progress",
  500:"(Q) lane(s) closed::n (small number)",
  501:"(Q) right lane(s) closed::n (small number)",
  502:"(Q) centre lane(s) closed::n (small number)",
  503:"(Q) left lane(s) closed::n (small number)",
  504:"hard shoulder closed",
  637:"emergency lane closed",
  41:"(Q) overtaking lane(s) closed::n (small number)",
  641:"one lane closed",
  505:"two lanes closed",
  506:"three lanes closed",
  514:"carriageway reduced (from Q lanes) one lane::n (small number)",
  515:"carriageway reduced (from Q lanes) two lanes::n (small number)",
  516:"carriageway reduced (from Q lanes) three lanes::n (small number)",
  601:"contraflow. Carriageway reduced (from Q lanes) to one lane::n (small number)",
  602:"contraflow. Carriageway reduced (from Q lanes) to two lanes::n (small number)",
  603:"contraflow. Carriageway reduced (from Q lanes) to three lanes::n (small number)",
  735:"closed due to (Q sets of) roadworks::n (small number)",
  736:"(Q sets of) roadworks. Right lane closed::n (small number)",
  737:"(Q sets of) roadworks. Centre lane closed::n (small number)",
  738:"(Q sets of) roadworks. Left lane closed::n (small number)",
  739:"(Q sets of) roadworks. Hard shoulder closed::n (small number)",
  740:"(Q sets of) roadworks. Two lanes closed::n (small number)",
  741:"(Q sets of) roadworks. Three lanes closed::n (small number)",
  51:"roadworks, (Q) overtaking lane(s) closed::n (small number)",
  743:"roadworks. Carriageway reduced (from Q lanes) to one lane::n (small number)",
  744:"roadworks. Carriageway reduced (from Q lanes) to two lanes::n (small number)",
  745:"roadworks. Carriageway reduced (from Q lanes) to three lanes::n (small number)",
  776:"resurfacing work. Carriageway reduced (from Q lanes) to one lane::n (small number)",
  777:"resurfacing work. Carriageway reduced (from Q lanes) to two lanes::n (small number)",
  778:"resurfacing work. Carriageway reduced (from Q lanes) to three lanes::n (small number)",
  793:"(Q sets of) road marking work. Right lane closed::n (small number)",
  794:"(Q sets of) road marking work. Centre lane closed::n (small number)",
  795:"(Q sets of) road marking work. Left lane closed::n (small number)",
  796:"(Q sets of) road marking work. Hard shoulder closed::n (small number)",
  797:"(Q sets of) road marking work. Two lanes closed::n (small number)",
  798:"(Q sets of) road marking work. Three lanes closed::n (small number)",
  835:"(Q sets of) slow moving maintenance vehicles. Right lane closed::n (small number)",
  836:"(Q sets of) slow moving maintenance vehicles. Centre lane closed::n (small number)",
  837:"(Q sets of) slow moving maintenance vehicles. Left lane closed::n (small number)",
  838:"(Q sets of) slow moving maintenance vehicles. Two lanes closed::n (small number)",
  839:"(Q sets of) slow moving maintenance vehicles. Three lanes closed::n (small number)",
  799:"closed for bridge demolition work (at Q bridges)::n (small number)",
  947:"road closed due to landslips",
  957:"road closed due to burst water main",
  965:"closed due to serious fire",
  951:"subsidence. Carriageway reduced (from Q lanes) to one lane::n (small number)",
  952:"subsidence. Carriageway reduced (from Q lanes) to two lanes::n (small number)",
  953:"subsidence. Carriageway reduced (from Q lanes) to three lanes::n (small number)",
  956:"closed due to sewer collapse",
  961:"closed due to gas leak",
  969:"closed for clearance work",
  1021:"snow on the road. Carriageway reduced (from Q lanes) to one lane::n (small number)",
  1022:"snow on the road. Carriageway reduced (from Q lanes) to two lanes::n (small number)",
  1023:"snow on the road. Carriageway reduced (from Q lanes) to three lanes::n (small number)",
  241:"(Q) accident(s). Right lane blocked::n (small number)",
  242:"(Q) accident(s). Centre lane blocked::n (small number)",
  243:"(Q) accident(s). Left lane blocked::n (small number)",
  244:"(Q) accident(s). Hard shoulder blocked::n (small number)",
  245:"(Q) accident(s). Two lanes blocked::n (small number)",
  246:"(Q) accident(s). Three lanes blocked::n (small number)",
  303:"blocked by (Q) shed load(s)::n (small number)",
  304:"(Q) shed load(s). Right lane blocked::n (small number)",
  305:"(Q) shed load(s). Centre lane blocked::n (small number)",
  306:"(Q) shed load(s). Left lane blocked::n (small number)",
  307:"(Q) shed load(s). Hard shoulder blocked::n (small number)",
  308:"(Q) shed load(s). Two lanes blocked::n (small number)",
  309:"(Q) shed load(s). Three lanes blocked::n (small number)",
  369:"blocked by (Q) overturned vehicle(s)::n (small number)",
  370:"(Q) overturned vehicle(s). Right lane blocked::n (small number)",
  371:"(Q) overturned vehicle(s). Centre lane blocked::n (small number)",
  372:"(Q) overturned vehicle(s). Left lane blocked::n (small number)",
  373:"(Q) overturned vehicle(s). Two lanes blocked::n (small number)",
  374:"(Q) overturned vehicle(s). Three lanes blocked::n (small number)",
  323:"blocked by (Q) broken down vehicle(s).::n (small number)",
  324:"(Q) broken down vehicle(s). Right lane blocked::n (small number)",
  325:"(Q) broken down lane vehicle(s). Centre lane blocked::n (small number)",
  326:"(Q) broken down vehicle(s). Left lane blocked::n (small number)",
  327:"(Q) broken down vehicle(s). Hard shoulder blocked::n (small number)",
  328:"(Q) broken down vehicle(s). Two lanes blocked::n (small number)",
  329:"(Q) broken down vehicle(s). Three lanes blocked::n (small number)",
  402:"blocked",
  520:"(Q) lane(s) blocked::n (small number)",
  507:"(Q) right lane(s) blocked::n (small number)",
  508:"(Q) centre lane(s) blocked::n (small number)",
  509:"(Q) left lane(s) blocked::n (small number)",
  510:"hard shoulder blocked",
  642:"emergency lane blocked",
  42:"(Q) overtaking lane(s) blocked::n (small number)",
  646:"One lane blocked",
  511:"Two lanes blocked",
  512:"three lanes blocked",
  980:"blocked by (Q) obstruction(s) on the road::n (small number)",
  982:"blocked due to spillage on roadway",
  925:"blocked by storm damage",
  926:"blocked by (Q) fallen trees::n (small number)",
  987:"blocked by fallen power cables",
  517:"contraflow",
  518:"narrow lanes",
  519:"contraflow with narrow lanes",
  513:"single alternate line traffic",
  746:"(Q sets of) roadworks. Contraflow::n (small number)",
  742:"(Q sets of) roadworks. Single alternate line traffic::n (small number)",
  779:"(Q sections of) resurfacing work. Contraflow::n (small number)",
  775:"(Q sections of) resurfacing work. Single alternate line traffic::n (small number)",
  954:"subsidence. Contraflow in operation",
  638:"turning lane closed",
  643:"turning lane blocked",
  639:"crawler lane closed",
  640:"slow vehicle lane closed",
  678:"heavy vehicle lane closed",
  644:"crawler lane blocked",
  645:"slow vehicle lane blocked",
  679:"heavy vehicle lane blocked",
  657:"lane blockages cleared",
  631:"road cleared",
  658:"contraflow removed",
  467:"reopened",
  630:"open",
  624:"lane closures removed",
  664:"carriageway closed",
  665:"both directions closed",
  625:"message cancelled",
  479:"parallel carriageway closed",
  480:"right-hand parallel carriageway closed",
  481:"left-hand parallel carriageway closed",
  482:"express lanes closed",
  483:"through traffic lanes closed",
  484:"local lanes closed",
  486:"parallel carriageway blocked",
  487:"right-hand parallel carriageway blocked",
  488:"left-hand parallel carriageway blocked",
  489:"express lanes blocked",
  490:"through traffic lanes blocked",
  491:"local lanes blocked",
  1982:"bus lane closed",
  676:"bus lane blocked",
  26:"bridge blocked",
  27:"tunnel blocked",
  663:"all carriageways cleared",
  634:"all carriageways reopened",
  672:"message cancelled",
  407:"(Q th) exit slip road closed::n (small number)",
  474:"(Q) exit slip road(s) closed::n (small number)",
  475:"(Q th) exit slip road blocked::n (small number)",
  476:"exit blocked",
  408:"slip roads closed",
  477:"slip roads blocked",
  409:"slip road restrictions",
  478:"connecting carriageway closed",
  485:"connecting carriageway blocked",
  633:"exit reopened",
  466:"slip roads reopened",
  673:"message cancelled",
  406:"(Q th) entry slip road closed::n (small number)",
  471:"(Q) entry slip road(s) closed::n (small number)",
  472:"(Q th) entry slip road blocked::n (small number)",
  473:"entry blocked",
  632:"entry reopened",
  399:"message cancelled",
  492:"no motor vehicles",
  493:"restrictions",
  627:"no motor vehicles without catalytic converters",
  628:"no motor vehicles with even-numbered registration plates",
  629:"no motor vehicles with odd-numbered registration plates",
  405:"no through traffic",
  404:"no through traffic for heavy lorries (over Q)::W tonnes",
  1332:"smog alert",
  1338:"no motor vehicles due to smog alert",
  469:"closed ahead",
  470:"blocked ahead",
  2000:"closed due to smog alert (until Q)::H time",
  1527:"closed due to major event",
  1541:"closed due to sports meeting",
  1555:"closed due to fair",
  1559:"closed due to parade",
  1563:"closed due to strike",
  1567:"closed due to demonstration",
  1580:"closed due to security alert",
  1485:"closed due to security incident",
  938:"closed due to flooding",
  943:"closed due to avalanches",
  993:"closed due to avalanche risk",
  995:"closed due to ice build-up",
  945:"closed due to rockfalls",
  949:"closed due to subsidence",
  2013:"service area busy",
  20:"service area overcrowded, drive to another service area",
  22:"service area, fuel station closed",
  23:"service area, restaurant closed",
  24:"bridge closed",
  25:"tunnel closed",
  403:"closed for heavy vehicles (over Q)::W tonnes",
  494:"closed for heavy lorries (over Q)::W tonnes",
  661:"use of hard shoulder allowed",
  1854:"traffic regulations have been changed",
  28:"road closed intermittently",
  1971:"police directing traffic",
  1972:"bus lane available for all vehicles",
  1973:"police directing traffic via the bus-lane",
  1978:"heavy vehicle lane available for all vehicles",
  1979:"police directing traffic via the heavy vehicle lane",
  662:"normal lane regulations restored",
  1974:"allow emergency vehicles to pass",
  1977:"allow emergency vehicles to pass in the heavy vehicle lane",
  1961:"allow emergency vehicles to pass in the carpool lane",
  1212:"closed for high-sided vehicles due to strong winds (Q)::of up to S km/h",
  660:"lane restrictions lifted",
  1215:"restrictions for high-sided vehicles lifted",
  680:"reopened for through traffic",
  36:"fuel station reopened",
  37:"restaurant reopened",
  635:"motor vehicle restrictions lifted",
  40:"smog alert ended",
  636:"traffic restrictions lifted {reopened for all traffic}",
  468:"message cancelled",
  647:"(Q person) carpool lane in operation::n (small number)",
  648:"(Q person) carpool lane closed::n (small number)",
  649:"(Q person) carpool lane blocked::n (small number)",
  671:"bus lane available for carpools (with at least Q occupants)::n (small number)",
  650:"carpool restrictions changed (to Q persons per vehicle)::n (small number)",
  1962:"carpool lane available for all vehicles",
  1963:"police directing traffic via the carpool lane",
  2006:"closed for vehicles with less than three occupants {not valid for lorries}",
  2007:"closed for vehicles with only one occupant {not valid for lorries}",
  659:"(Q person) carpool restrictions lifted::n (small number)",
  2029:"message cancelled",
  701:"(Q sets of) roadworks::n (small number)",
  702:"(Q sets of) major roadworks::n (small number)",
  802:"(Q sets of) long-term roadworks::n (small number)",
  803:"(Q sets of) construction work::n (small number)",
  704:"(Q sections of) resurfacing work::n (small number)",
  705:"(Q sets of) central reservation work::n (small number)",
  703:"(Q sets of) maintenance work::n (small number)",
  853:"roadwork clearance in progress",
  707:"bridge maintenance work (at Q bridges)::n (small number)",
  805:"bridge demolition work (at Q bridges)::n (small number)",
  709:"(Q sections of) blasting work::n (small number)",
  52:"(Q sets of) roadworks on the hard shoulder::n (small number)",
  53:"(Q sets of) roadworks in the emergency lane::n (small number)",
  815:"(Q sets of) roadworks during the day time::n (small number)",
  816:"(Q sets of) roadworks during off-peak periods::n (small number)",
  817:"(Q sets of) roadworks during the night::n (small number)",
  821:"(Q sets of) resurfacing work during the day time::n (small number)",
  822:"(Q sets of) resurfacing work during off- peak periods::n (small number)",
  823:"(Q sets of) resurfacing work during the night::n (small number)",
  708:"(Q sets of) temporary traffic lights::n (small number)",
  806:"(Q sets of) water main work::n (small number)",
  807:"(Q sets of) gas main work::n (small number)",
  808:"(Q sets of) work on buried cables::n (small number)",
  809:"(Q sets of) work on buried services::n (small number)",
  810:"new roadworks layout",
  855:"road layout unchanged",
  811:"new road layout",
  854:"maintenance work cleared",
  800:"roadworks cleared",
  801:"message cancelled",
  901:"(Q) obstruction(s) on roadway {something that does block the road or part of it}::n (small number)",
  902:"(Q) obstructions on the road. Danger::n (small number)",
  981:"(Q) obstructions on the road. Passable with care::n (small number)",
  61:"(Q) object(s) on roadway {something that does not necessarily block the road or part of it} ::n (small number)",
  63:"(Q) object(s) on the road. Danger::n (small number)",
  210:"(Q) shed load(s)::n (small number)",
  359:"(Q) shed load(s). Danger::n (small number)",
  903:"spillage on the road",
  984:"spillage on the road. Danger",
  904:"storm damage",
  986:"storm damage. Danger",
  972:"storm damage expected",
  905:"(Q) fallen trees::n (small number)",
  906:"(Q) fallen trees. Danger::n (small number)",
  973:"fallen power cables",
  989:"fallen power cables. Danger",
  907:"flooding",
  900:"flooding expected",
  908:"flooding. Danger",
  974:"sewer overflow",
  990:"sewer overflow. Danger",
  909:"flash floods",
  910:"danger of flash floods",
  991:"flash floods. Danger",
  911:"avalanches",
  992:"avalanches. Danger",
  912:"avalanche risk",
  994:"avalanche risk. Danger",
  975:"ice build-up",
  913:"rockfalls",
  998:"rockfalls. Danger",
  914:"landslips",
  999:"landslips. Danger",
  976:"mud slide",
  915:"earthquake damage",
  1000:"earthquake damage. Danger",
  917:"subsidence",
  1026:"subsidence. Danger",
  918:"(Q) collapsed sewer(s)::n (small number)",
  1030:"sewer collapse. Danger",
  919:"burst water main",
  1031:"burst water main. Danger",
  62:"(Q) burst pipe(s)::n (small number)",
  64:"burst pipe. Danger",
  920:"gas leak",
  1032:"gas leak. Danger",
  977:"grass fire",
  921:"serious fire",
  1033:"serious fire. Danger",
  978:"air crash",
  979:"rail crash",
  983:"spillage on the road. Passable with care",
  985:"storm damage. Passable with care",
  927:"(Q) fallen tree(s). Passable with care::n (small number)",
  988:"fallen power cables. Passable with care",
  942:"flooding. Passable with care",
  944:"avalanches. Passable with care (above Q hundred metres)::n (small number)",
  996:"ice build-up. Passable with care (above Q hundred metres)::n (small number)",
  946:"rockfalls. Passable with care",
  948:"landslips. Passable with care",
  955:"subsidence. Passable with care",
  950:"subsidence. Single alternate line traffic",
  997:"ice build-up. Single alternate traffic",
  1709:"spillage occurring from moving vehicle",
  1700:"(Q) slow moving maintenance vehicle(s)::n (small number)",
  898:"obstruction warning withdrawn",
  899:"clearance work in progress, road free again",
  970:"road free again",
  1712:"road cleared",
  1084:"house fire",
  1086:"vehicle stuck under bridge",
  971:"message cancelled",
  922:"animals on roadway",
  1471:"sightseers obstructing access",
  1472:"people on roadway",
  1473:"children on roadway",
  1474:"cyclists on roadway",
  923:"animals on the road. Danger",
  1482:"people on roadway. Danger",
  1483:"children on roadway. Danger",
  1484:"cyclists on roadway. Danger",
  1067:"large animals on roadway",
  1068:"herds of animals on roadway",
  852:"construction traffic merging",
  856:"construction traffic merging. Danger",
  706:"(Q sets of) road marking work::n (small number)",
  824:"(Q sets of) road marking work. Danger::n (small number)",
  1771:"warning cleared",
  857:"(Q) unprotected accident area(s)::n (small number)",
  858:"danger of (Q) unprotected accident area(s)::n (small number)",
  859:"(Q) unlit vehicle(s) on the road::n (small number)",
  860:"danger of (Q) unlit vehicle(s) on the road::n (small number)",
  861:"snow and ice debris",
  862:"danger of snow and ice debris",
  2030:"message cancelled",
  1035:"impassable (above Q hundred metres)::n (small number)",
  1036:"almost impassable (above Q hundred metres)::n (small number)",
  1037:"extremely hazardous driving conditions (above Q hundred metres)::n (small number)",
  1073:"extremely hazardous driving conditions expected (above Q hundred meters)::n (small number)",
  1001:"hazardous driving conditions (above Q hundred metres)::n (small number)",
  1038:"difficult driving conditions (above Q hundred metres)::n (small number)",
  1039:"passable with care (up to Q hundred metres)::n (small number)",
  1040:"passable (up to Q hundred metres)::n (small number)",
  1063:"impassable for heavy vehicles (over Q)::W tonnes",
  1064:"impassable (above Q hundred metres) for vehicles with trailers::n (small number)",
  1041:"surface water hazard",
  1002:"danger of aquaplaning",
  1003:"slippery road (above Q hundred metres)::n (small number)",
  1004:"mud on road",
  1055:"mud on road. Danger",
  1005:"leaves on road",
  1042:"loose sand on road",
  1043:"loose chippings",
  1056:"loose chippings. Danger",
  1044:"oil on road",
  1057:"oil on road. Danger",
  1045:"petrol on road",
  1058:"petrol on road. Danger",
  916:"road surface in poor condition",
  1059:"road surface in poor condition. Danger",
  1006:"ice (above Q hundred metres)::n (small number)",
  1007:"danger of ice (above Q hundred metres)::n (small number)",
  1047:"icy patches (above Q hundred metres)::n (small number)",
  1048:"danger of icy patches (above Q hundred metres)::n (small number)",
  1008:"black ice (above Q hundred metres)::n (small number)",
  1050:"danger of black ice (above Q hundred metres)::n (small number)",
  1009:"freezing rain (above Q hundred metres)::n (small number)",
  1074:"freezing rain expected (above Q hundred metres)::n (small number)",
  1010:"wet and icy roads (above Q hundred metres)::n (small number)",
  1011:"slush (above Q hundred metres)::n (small number)",
  1012:"snow on the road (above Q hundred metres)::n (small number)",
  1013:"packed snow (above Q hundred metres)::n (small number)",
  1014:"fresh snow (above Q hundred metres)::n (small number)",
  1015:"deep snow (above Q hundred metres)::n (small number)",
  1016:"snow drifts (above Q hundred metres)::n (small number)",
  1018:"slippery road (above Q hundred metres) due to snow::n (small number)",
  1019:"slippery road (above Q hundred metres) due to frost::n (small number)",
  1017:"slippery due to spillage on roadway",
  1054:"slippery due to loose sand on roadway",
  1060:"icy patches (above Q hundred metres) on bridges::n (small number)",
  1061:"danger of icy patches (above Q hundred metres) on bridges::n (small number)",
  1062:"icy patches (above Q hundred metres) on bridges, in shaded areas and on slip roads::n (small number)",
  1020:"road blocked by snow (above Q hundred metres)::n (small number)",
  1075:"danger of road being blocked by snow (above Q hundred metres)::n (small number)",
  1024:"conditions of road surface improved",
  1070:"snow cleared",
  1065:"driving conditions improved",
  1069:"skid hazard reduced",
  1165:"rain changing to snow",
  1166:"snow changing to rain",
  1025:"message cancelled",
  1083:"current temperature (Q)::T degrees Celsius",
  1115:"heavy frost",
  1116:"frost",
  1079:"temperature falling rapidly (to Q)::T degrees Celsius",
  1080:"extreme heat (up to Q)::T degrees Celsius",
  1081:"extreme cold (of Q)::T degrees Celsius",
  1082:"less extreme temperatures",
  1127:"message cancelled",
  1132:"damaging hail (visibility reduced to Q)::less than V metres",
  1174:"damaging hail (with visibility reduced to Q) expected::less than V metres",
  1106:"hail (visibility reduced to Q)::less than V metres",
  1107:"sleet (visibility reduced to Q)::less than V metres",
  1108:"thunderstorms (visibility reduced to Q)::less than V metres",
  1128:"winter storm (visibility reduced to Q)::less than V metres",
  1130:"blizzard (visibility reduced to Q)::less than V metres",
  1173:"blizzard (with visibility reduced to Q) expected::less than V metres",
  1101:"heavy snowfall (Q)::of up to D millimetres",
  1170:"heavy snowfall (Q) expected::of up to D millimetres",
  1134:"heavy snowfall. Visibility reduced (to Q)::less than V metres",
  1102:"heavy snowfall (Q). Visibility reduced to <30 m::of up to D millimetres",
  1103:"heavy snowfall (Q). Visibility reduced to <50 m::of up to D millimetres",
  1104:"snowfall (Q)::of up to D millimetres",
  1135:"snowfall. Visibility reduced (to Q)::less than V metres",
  1105:"snowfall (Q). Visibility reduced to <100 m::of up to D millimetres",
  1109:"heavy rain (Q)::of up to D millimetres",
  1171:"heavy rain (Q) expected::of up to D millimetres",
  1136:"heavy rain. Visibility reduced (to Q)::less than V metres",
  1110:"heavy rain (Q). Visibility reduced to <30 m::of up to D millimetres",
  1111:"heavy rain (Q). Visibility reduced to <50 m::of up to D millimetres",
  1112:"rain (Q)::of up to D millimetres",
  1137:"rain. Visibility reduced (to Q)::less than V metres",
  1113:"rain (Q). Visibility reduced to <100 m::of up to D millimetres",
  1114:"showers (visibility reduced to Q)::less than V metres",
  1318:"visibility reduced (to Q)::less than V metres",
  1319:"visibility reduced to <30 m",
  1320:"visibility reduced to <50 m",
  1321:"visibility reduced to <100 m",
  1175:"reduced visibility (to Q) expected::less than V metres",
  1322:"white out (visibility reduced to Q)::less than V metres",
  1323:"blowing snow (visibility reduced to Q)::less than V metres",
  1309:"smoke hazard (visibility reduced to Q)::less than V metres",
  1324:"spray hazard (visibility reduced to Q)::less than V metres",
  1325:"low sun glare",
  1310:"blowing dust (visibility reduced to Q)::less than V metres",
  1326:"sandstorms (visibility reduced to Q)::less than V metres",
  1340:"swarms of insects (visibility reduced to Q)::less than V metres",
  1301:"dense fog (visibility reduced to Q)::less than V metres",
  1177:"dense fog (with visibility reduced to Q) expected::less than V metres",
  1304:"fog (visibility reduced to Q)::less than V metres",
  1307:"patchy fog (visibility reduced to Q)::less than V metres",
  1178:"patchy fog (with visibility reduced to Q) expected::less than V metres",
  1308:"freezing fog (visibility reduced to Q)::less than V metres",
  1337:"freezing fog (visibility reduced to Q). Slippery roads::less than V metres",
  1176:"freezing fog expected (with visibility reduced to Q). Danger of slippery roads::less than V metres",
  1302:"dense fog. Visibility reduced to <30 m",
  1303:"dense fog. Visibility reduced to <50 m",
  1305:"fog. Visibility reduced to <100 m",
  1312:"snowfall and fog (visibility reduced to Q)::less than V metres",
  1346:"fog forecast withdrawn",
  1345:"fog clearing",
  1313:"visibility improved",
  1179:"visibility expected to improve",
  1172:"weather expected to improve",
  1126:"weather situation improved",
  1180:"adverse weather warning withdrawn",
  1314:"message cancelled",
  1201:"tornadoes",
  1202:"hurricane force winds (Q)::of up to S km/h",
  1203:"gales (Q)::of up to S km/h",
  1204:"storm force winds (Q)::of up to S km/h",
  1205:"strong winds (Q)::of up to S km/h",
  1209:"gusty winds (Q)::of up to S km/h",
  1210:"crosswinds (Q)::of up to S km/h",
  1211:"strong winds (Q) affecting high-sided vehicles::of up to S km/h",
  1190:"severe smog",
  1191:"severe exhaust pollution",
  1217:"tornado warning ended",
  1213:"strong winds easing",
  1214:"message cancelled",
  1501:"major event",
  1590:"several major events",
  1502:"sports event meeting",
  1450:"international sports meeting",
  1451:"match",
  1452:"tournament",
  1453:"athletics meeting",
  1454:"ball game",
  1455:"boxing tournament",
  1456:"bull fight",
  1457:"cricket match",
  1458:"cycle race",
  1459:"football match",
  1460:"golf tournament",
  1461:"marathon",
  1462:"race meeting",
  1463:"rugby match",
  1464:"show jumping",
  1465:"tennis tournament",
  1466:"water sports meeting",
  1467:"winter sports meeting",
  1503:"show",
  1504:"festival",
  1505:"exhibition",
  1507:"market",
  1506:"fair",
  1468:"funfair",
  1469:"trade fair",
  1508:"ceremonial event",
  1509:"state occasion",
  1510:"parade",
  1470:"procession",
  1511:"crowd",
  1475:"strike",
  1512:"march",
  1513:"demonstration",
  1514:"public disturbance",
  1591:"information about major event no longer valid",
  1493:"sports traffic cleared",
  1496:"traffic disruption cleared",
  1592:"automobile race",
  1593:"baseball game",
  1594:"basketball game",
  1595:"boat race",
  1596:"concert",
  1597:"hockey game",
  1585:"message cancelled",
  1515:"security alert",
  1476:"security incident",
  1477:"police checkpoint",
  1516:"bomb alert",
  1478:"terrorist incident",
  1479:"gunfire on roadway, danger",
  1480:"civil emergency",
  1481:"air raid, danger",
  1494:"evacuation",
  1587:"air raid warning cancelled",
  1492:"security alert withdrawn",
  1588:"civil emergency cancelled",
  2033:"message cancelled",
  1601:"delays (Q)::of up to M minutes",
  1607:"delays (Q) expected::of up to M minutes",
  1650:"delays (Q) possible::of up to M minutes",
  1621:"delays up to 5 minutes",
  1622:"delays up to 10 minutes",
  1602:"delays up to 15 minutes",
  1623:"delays up to 20 minutes",
  1624:"delays up to 25 minutes",
  1603:"delays up to 30 minutes",
  1625:"delays up to 40 minutes",
  1626:"delays up to 50 minutes",
  1604:"delays up to one hour",
  1627:"delays up to 90 minutes",
  1605:"delays up to two hours",
  1628:"delays up to three hours",
  1629:"delays up to four hours",
  1630:"delays up to five hours",
  1606:"delays of several hours",
  1608:"long delays (Q)::of up to M minutes",
  1631:"very long delays (Q)::of up to M minutes",
  1632:"delays of uncertain duration",
  247:"accident. Delays (Q)::of up to M minutes",
  248:"accident. Delays (Q) expected::of up to M minutes",
  249:"accident. Long delays (Q)::of up to M minutes",
  200:"multi vehicle pile up. Delays (Q)::of up to M minutes",
  275:"vehicles slowing to look at accident. Delays (Q)::of up to M minutes",
  276:"vehicles slowing to look at accident. Delays (Q) expected::of up to M minutes",
  277:"vehicles slowing to look at accident. Long delays (Q)::of up to M minutes",
  310:"shed load. Delays (Q)::of up to M minutes",
  311:"shed load. Delays (Q) expected::of up to M minutes",
  312:"shed load. Long delays (Q)::of up to M minutes",
  375:"overturned vehicle. Delays (Q)::of up to M minutes",
  376:"overturned vehicle. Delays (Q) expected::of up to M minutes",
  377:"overturned vehicle. Long delays (Q)::of up to M minutes",
  388:"Delays (Q) due to earlier accident::of up to M minutes",
  390:"Long delays (Q) due to earlier accident::of up to M minutes",
  330:"broken down vehicle. Delays (Q)::of up to M minutes",
  331:"broken down vehicle. Delays (Q) expected::of up to M minutes",
  332:"broken down vehicle. Long delays (Q)::of up to M minutes",
  435:"closed ahead. Delays (Q)::of up to M minutes",
  436:"closed ahead. Delays (Q) expected::of up to M minutes",
  437:"closed ahead. Long delays (Q)::of up to M minutes",
  463:"blocked ahead. Delays (Q)::of up to M minutes",
  464:"blocked ahead. Delays (Q) expected::of up to M minutes",
  465:"blocked ahead. Long delays (Q)::of up to M minutes",
  747:"roadworks. Delays (Q)::of up to M minutes",
  748:"roadworks. Delays (Q) expected::of up to M minutes",
  749:"roadworks. Long delays (Q)::of up to M minutes",
  780:"resurfacing work. Delays (Q)::of up to M minutes",
  781:"resurfacing work. Delays (Q) expected::of up to M minutes",
  782:"resurfacing work. Long delays (Q)::of up to M minutes",
  840:"water main work. Delays (Q)::of up to M minutes",
  841:"water main work. Delays (Q) expected::of up to M minutes",
  842:"water main work. Long delays (Q)::of up to M minutes",
  843:"gas main work. Delays (Q)::of up to M minutes",
  844:"gas main work. Delays (Q) expected::of up to M minutes",
  845:"gas main work. Long delays (Q)::of up to M minutes",
  846:"work on buried cables. Delays (Q)::of up to M minutes",
  847:"work on buried cables. Delays (Q) expected::of up to M minutes",
  848:"work on buried cables. Long delays (Q)::of up to M minutes",
  849:"work on buried services. Delays (Q)::of up to M minutes",
  850:"work on buried services. Delays (Q) expected::of up to M minutes",
  851:"work on buried services. Long delays (Q)::of up to M minutes",
  939:"flooding. Delays (Q)::of up to M minutes",
  940:"flooding. Delays (Q) expected::of up to M minutes",
  941:"flooding. Long delays (Q)::of up to M minutes",
  1027:"sewer collapse. Delays (Q)::of up to M minutes",
  1028:"sewer collapse. Delays (Q) expected::of up to M minutes",
  1029:"sewer collapse. Long delays (Q)::of up to M minutes",
  958:"burst water main. Delays (Q)::of up to M minutes",
  959:"burst water main. Delays (Q) expected::of up to M minutes",
  960:"burst water main. Long delays (Q)::of up to M minutes",
  962:"gas leak. Delays (Q)::of up to M minutes",
  963:"gas leak. Delays (Q) expected::of up to M minutes",
  964:"gas leak. Long delays (Q)::of up to M minutes",
  966:"serious fire. Delays (Q)::of up to M minutes",
  967:"serious fire. Delays (Q) expected::of up to M minutes",
  968:"serious fire. Long delays (Q)::of up to M minutes",
  1528:"major event. Delays (Q)::of up to M minutes",
  1529:"major event. Delays (Q) expected::of up to M minutes",
  1530:"major event. Long delays (Q)::of up to M minutes",
  1542:"sports meeting. Delays (Q)::of up to M minutes",
  1543:"sports meeting. Delays (Q) expected::of up to M minutes",
  1544:"sports meeting. Long delays (Q)::of up to M minutes",
  1556:"fair. Delays (Q)::of up to M minutes",
  1557:"fair. Delays (Q) expected::of up to M minutes",
  1558:"fair. Long delays (Q)::of up to M minutes",
  1560:"parade. Delays (Q)::of up to M minutes",
  1561:"parade. Delays (Q) expected::of up to M minutes",
  1562:"parade. Long delays (Q)::of up to M minutes",
  1564:"strike. Delays (Q)::of up to M minutes",
  1565:"strike. Delays (Q) expected::of up to M minutes",
  1566:"strike. Long delays (Q)::of up to M minutes",
  1568:"demonstration. Delays (Q)::of up to M minutes",
  1569:"demonstration. Delays (Q) expected::of up to M minutes",
  1570:"demonstration. Long delays (Q)::of up to M minutes",
  1581:"security alert. Delays (Q)::of up to M minutes",
  1582:"security alert. Delays (Q) expected::of up to M minutes",
  1583:"security alert. Long delays (Q)::of up to M minutes",
  1486:"security incident. Delays (Q)::of up to M minutes",
  1487:"security incident. Delays (Q) expected::of up to M minutes",
  1488:"security incident. Long delays (Q)::of up to M minutes",
  1489:"police checkpoint. Delays (Q)::of up to M minutes",
  1490:"police checkpoint. Delays (Q) expected::of up to M minutes",
  1491:"police checkpoint. Long delays (Q)::of up to M minutes",
  1609:"delays (Q) for heavy vehicles::of up to M minutes",
  91:"delays (Q) for cars::of up to M minutes",
  1642:"delays (Q) for heavy lorr(y/ies)::of up to M minutes",
  1610:"delays up to 15 minutes for heavy lorr(y/ies)",
  1611:"delays up to 30 minutes for heavy lorr(y/ies)",
  1612:"delays up to one hour for heavy lorr(y/ies)",
  1613:"delays up to two hours for heavy lorr(y/ies)",
  1614:"delays of several hours for heavy lorr(y/ies)",
  1643:"delays (Q) for buses::of up to M minutes",
  1653:"long delays expected",
  1654:"very long delays expected",
  1757:"abnormal load. Delays (Q) expected::of up to M minutes",
  1758:"abnormal load. Long delays (Q)::of up to M minutes",
  1756:"abnormal load. Delays (Q)::of up to M minutes",
  1740:"abnormal load causing slow traffic. Delays (Q)::of up to M minutes",
  1759:"convoy causing delays (Q)::of up to M minutes",
  1760:"convoy. Delays (Q) expected::of up to M minutes",
  1761:"convoy causing long delays (Q)::of up to M minutes",
  1741:"convoy causing slow traffic. Delays (Q)::of up to M minutes",
  1817:"traffic lights not working. Delays (Q)::of up to M minutes",
  1818:"traffic lights not working. Delays (Q) expected::of up to M minutes",
  1819:"traffic lights not working. Long delays (Q)::of up to M minutes",
  1868:"traffic lights working incorrectly. Delays (Q)::of up to M minutes",
  1869:"traffic lights working incorrectly. Delays (Q) expected::of up to M minutes",
  1870:"traffic lights working incorrectly. Long delays (Q)::of up to M minutes",
  1876:"temporary traffic lights not working. Delays (Q)::of up to M minutes",
  1877:"temporary traffic lights not working. Delays (Q) expected::of up to M minutes",
  1878:"temporary traffic lights not working. Long delays (Q)::of up to M minutes",
  1880:"traffic signal control computer not working. Delays (Q)::of up to M minutes",
  1884:"traffic signal control computer not working. Delays (Q) expected::of up to M minutes",
  1885:"traffic signal control computer not working. Long delays (Q)::of up to M minutes",
  1830:"level crossing failure. Delays (Q)::of up to M minutes",
  1831:"level crossing failure. Delays (Q) expected::of up to M minutes",
  1832:"level crossing failure. Long delays (Q)::of up to M minutes",
  1858:"Snowplough. Delays (Q)::of up to M minutes",
  1648:"delays cleared",
  1663:"delay expected to be cleared",
  1620:"message cancelled",
  1634:"cancellations",
  1652:"cancellations expected",
  1615:"service suspended (until Q)::H time",
  1633:"delayed until further notice",
  1616:"(Q) service withdrawn::H time",
  1617:"(Q) service(s) fully booked::H time",
  1655:"all services fully booked (until Q)::H time",
  1906:"park and ride service operating (until Q)::H time",
  1635:"park and ride service not operating (until Q)::H time",
  1636:"special public transport services operating (until Q)::H time",
  1637:"normal services not operating (until Q)::H time",
  1638:"rail services not operating (until Q)::H time",
  1720:"rail services irregular",
  1657:"rail services irregular. Delays (Q)::of up to M minutes",
  1658:"bus services irregular. Delays (Q)::of up to M minutes",
  1639:"bus services not operating (until Q)::H time",
  1649:"rapid transit service not operating (until Q)::H time",
  1640:"shuttle service operating (until Q)::H time",
  1641:"free shuttle service operating (until Q)::H time",
  1659:"underground services irregular",
  1651:"underground service not operating (until Q)::H time",
  2021:"service not operating, substitute service available",
  2022:"public transport strike",
  1721:"public transport services not operating",
  1661:"ferry service not operating (until Q)::H time",
  1618:"(Q) service(s) fully booked for heavy vehicles::H time",
  1644:"(Q) service(s) fully booked for heavy lorr(y/ies)::H time",
  1645:"(Q) service(s) fully booked for buses::H time",
  1660:"normal public transport services resumed",
  1619:"normal services resumed",
  2034:"message cancelled",
  1662:"park and ride trip time (Q)::of up to M minutes",
  1695:"current trip time (Q)::of up to M minutes",
  1696:"expected trip time (Q)::of up to M minutes",
  1656:"next arrival (Q)::H time",
  1901:"next departure (Q)::H time",
  1902:"next departure (Q) for heavy vehicles::H time",
  1646:"next departure (Q) for heavy lorr(y/ies)::H time",
  1647:"next departure (Q) for buses::H time",
  2035:"message cancelled",
  1701:"(Q) vehicle(s) on wrong carriageway::n (small number)",
  1704:"(Q) reckless driver(s)::n (small number)",
  1705:"(Q) prohibited vehicle(s) on the roadway::n (small number)",
  1706:"(Q) emergency vehicles::n (small number)",
  1707:"(Q) high-speed emergency vehicles::n (small number)",
  1708:"high-speed chase (involving Q vehicles)::n (small number)",
  1710:"objects falling from moving vehicle",
  804:"(Q sets of) slow moving maintenance vehicles::n (small number)",
  1765:"(Q) vehicle(s) carrying hazardous materials::n (small number)",
  1736:"(Q) vehicle(s) carrying hazardous materials. Danger::n (small number)",
  1768:"Vehicles carrying hazardous materials have to stop at next safe place!",
  681:"(Q) snowploughs::n (small number)",
  1711:"emergency vehicle warning cleared",
  1702:"dangerous vehicle warning cleared",
  1769:"hazardous load warning cleared",
  1703:"message cancelled",
  347:"(Q) over-height vehicle(s)::n (small number)",
  1739:"(Q) over-height load(s), danger::n (small number)",
  1751:"(Q) abnormal load(s)::n (small number)",
  1731:"(Q) abnormal load(s), danger::n (small number)",
  1752:"(Q) wide load(s)::n (small number)",
  1732:"(Q) wide load(s), danger::n (small number)",
  1753:"(Q) long load(s)::n (small number)",
  1733:"(Q) long load(s), danger::n (small number)",
  1754:"(Q) slow vehicle(s)::n (small number)",
  1734:"(Q) slow vehicle(s), danger::n (small number)",
  1764:"(Q) track-laying vehicle(s)::n (small number)",
  1735:"(Q) track-laying vehicle(s), danger::n (small number)",
  1767:"(Q) abnormal load(s). No overtaking::n (small number)",
  1755:"(Q) convoy(s)::n (small number)",
  1737:"(Q) convoy(s), danger::n (small number)",
  1766:"(Q) military convoy(s)::n (small number)",
  1738:"(Q) military convoy(s), danger::n (small number)",
  1770:"convoy cleared",
  1762:"exceptional load warning cleared",
  1763:"message cancelled",
  1801:"lane control signs not working",
  1838:"lane control signs working incorrectly",
  1839:"lane control signs operating",
  1840:"variable message signs not working",
  1841:"variable message signs working incorrectly",
  1842:"variable message signs operating",
  1802:"emergency telephones not working",
  1803:"emergency telephone number not working",
  1865:"emergency telephones out of order. Extra police patrols in operation",
  1866:"emergency telephones out of order. In emergency, wait for police patrol",
  1804:"(Q sets of) traffic lights not working::n (small number)",
  1805:"(Q sets of) traffic lights working incorrectly::n (small number)",
  1843:"(Q sets of) ramp control signals not working::n (small number)",
  1844:"(Q sets of) ramp control signals working incorrectly::n (small number)",
  1845:"(Q sets of) temporary traffic lights not working::n (small number)",
  1846:"(Q sets of) temporary traffic lights working incorrectly::n (small number)",
  1850:"lane control signs not working. Danger",
  1864:"lane control signs working incorrectly. Danger",
  1867:"(Q sets of) traffic lights not working. Danger::n (small number)",
  1875:"(Q sets of) traffic lights working incorrectly. Danger::n (small number)",
  1879:"(Q sets of) temporary traffic lights not working. Danger::n (small number)",
  1847:"traffic signal control computer not working",
  1848:"traffic signal timings changed",
  1806:"level crossing failure",
  1849:"tunnel ventilation not working",
  1833:"electronic signs repaired",
  1834:"emergency call facilities restored",
  1835:"traffic signals repaired",
  1836:"level crossing now working normally",
  1983:"power failure",
  1837:"message cancelled",
  1851:"temporary width limit (Q)::L metres",
  1861:"temporary height limit (Q)::L metres",
  1881:"temporary length limit (Q)::L metres",
  1871:"temporary axle load limit (Q)::W tonnes",
  1872:"temporary gross weight limit (Q)::W tonnes",
  1852:"temporary width limit lifted",
  1862:"temporary height limit lifted",
  1882:"temporary length limit lifted",
  1874:"temporary axle weight limit lifted",
  1873:"temporary gross weight limit lifted",
  1857:"message cancelled",
  1886:"normal parking restrictions lifted",
  1887:"special parking restrictions in force",
  1927:"no parking (until Q)::H time",
  1928:"special parking restrictions lifted",
  1883:"message cancelled",
  1903:"car park (Q) full::P percent",
  1922:"expect car park to be full",
  1888:"10% full",
  1889:"20% full",
  1890:"30% full",
  1891:"40% full",
  1892:"50% full",
  1893:"60% full",
  1894:"70% full",
  1895:"80% full",
  1896:"90% full",
  1918:"full",
  1904:"all car parks (Q) full::P percent",
  1924:"multi story car parks full",
  1905:"less than (Q) car parking spaces available::N (number)",
  1926:"no parking spaces available",
  1923:"expect no parking spaces available",
  1920:"only a few parking spaces available",
  1921:"(Q) parking spaces available::N (number)",
  1897:"less than 10 parking spaces available",
  1898:"less than 20 parking spaces available",
  1899:"less than 30 parking spaces available",
  1900:"less than 40 parking spaces available",
  1855:"less than 50 parking spaces available",
  1925:"no problems to report with park and ride services",
  1934:"no park and ride information available (until Q)::H time",
  1938:"park and ride information service resumed",
  1856:"no parking information available (until Q)::H time",
  2038:"message cancelled",
  1913:"switch your car radio (to Q)::k kHz",
  1908:"switch your car radio (to Q)::M MHz",
  1929:"urgent information will be given (at Q) on normal programme broadcasts::H time",
  1931:"detailed information will be given (at Q) on normal programme broadcasts::H time",
  1909:"alarm call: important new information on this frequency follows now in normal programme",
  1910:"alarm set: new information will be broadcast between these times in normal programme",
  1955:"reference to audio programmes no longer valid",
  1911:"message cancelled",
  1940:"additional regional information is provided by another TMC service",
  1941:"additional local information is provided by another TMC service",
  1942:"additional public transport information is provided by another TMC service",
  1943:"national traffic information is provided by another TMC service",
  1944:"this service provides major road information",
  1945:"this service provides regional travel information",
  1946:"this service provides local travel information",
  1947:"no detailed regional information provided by this service",
  1948:"no detailed local information provided by this service",
  1932:"detailed information is provided by another TMC service",
  1949:"no cross-border information provided by this service",
  1950:"information restricted to this area",
  1951:"no new traffic information available (until Q)::H time",
  1952:"no public transport information available",
  1953:"this TMC-service is being suspended (at Q)::H time",
  1954:"active TMC-service will resume (at Q)::H time",
  1930:"this TMC-service is not active (until Q)::H time",
  1914:"no information available (until Q)::H time",
  1916:"no information available (until Q) due to technical problems::H time",
  1956:"reference to other TMC services no longer valid",
  1957:"previous announcement about this or other TMC services no longer valid",
  1964:"rail Information service not available",
  1965:"rail information service resumed",
  1966:"rapid transit information service not available",
  1967:"rapid transit information service resumed",
  2039:"message cancelled",
  1915:"this message is for test purposes only (number Q), please ignore::n (small number)",
  1907:"(null event) {no event description, but location etc. given in message}",
  2047:"(null message) {completely silent message, see EN ISO 14819-1, 3.5.4}",
  2041:"nothing to report",
  2040:"message cancelled",
}
